### ISSUE TITLE
Crashes on load

### ISSUE THREAD

**Issue by pearofducks** [neoclide/coc-vetur#1]
```
Error: Cannot find module 'vscode-languageserver-protocol/lib/protocol.colorProvider.proposed'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:534:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1278:46)
    at Function.Module._load (module.js:464:25)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/pear/.config/coc/extensions/node_modules/vue-language-server/dist/services/vls.js:4:43)
    at Module._compile (module.js:633:30)
    at Module._compile (pkg/prelude/bootstrap.js:1213:32)
    at Object.Module._extensions..js (module.js:644:10)
[Info  - 12:33:31] Connection to server got closed. Server will restart.
pkg/prelude/bootstrap.js:1176
      throw error;
      ^
```

**Comment by chemzqm** [comment]
I've updated the version of vetur, try `:CocInstall coc-vetur` to update

**Comment by pearofducks** [comment]
Confirmed working now, thanks!
